TEAM_ABBREV = {
    "mci": "Man City",
    "manchester city": "Man City",
    "mancity": "Man City",
    "city": "Man City",
    "mun": "Man Utd",
    "manchester united": "Man Utd",
    "manchester utd": "Man Utd",
    "manutd": "Man Utd",
    "united": "Man Utd",
    "liv": "Liverpool",
    "liver": "Liverpool",
    "lfc": "Liverpool",
    "che": "Chelsea",
    "ars": "Arsenal",
    "gunners": "Arsenal",
    "tot": "Spurs",
    "tottenham": "Spurs",
    "Tottenham Hotspur": "Spurs",
    "lei": "Leicester",
    "whu": "West Ham",
    "hammers": "West Ham",
    "west ham united": "West Ham",
    "eve": "Everton",
    "avl": "Aston Villa",
    "villa": "Aston Villa",
    "Aston": "Aston Villa",
    "new": "Newcastle",
    "newcastle utd": "Newcastle",
    "newcastle united": "Newcastle",
    "nufc": "Newcastle",
    "bha": "Brighton",
    "brighton": "Brighton",
    "brighton & hove albion": "Brighton",
    "wol": "Wolves",
    "wolverhampton": "Wolves",
    "Wolverhampton Wanderers": "Wolves",
    "sou": "Southampton",
    "saints": "Southampton",
    "cry": "Crystal Palace",
    "palace": "Crystal Palace",
    "cpfc": "Crystal Palace",
    "crystal": "Crystal Palace",
    "ful": "Fulham",
    "bou": "Bournemouth",
    "AFC Bournemouth": "Bournemouth",
    "bur": "Burnley",
    "lee": "Leeds",
    "Leeds United": "Leeds",
    "lufc": "Leeds",
    "nor": "Norwich",
    "Norwich City": "Norwich",
    "ncfc": "Norwich",
    "wat": "Watford",
    "bre": "Brentford",
    "nffc": "Nott'm Forest",
    "nottingham": "Nott'm Forest",
    "forest": "Nott'm Forest",
    "nott'm": "Nott'm Forest",
}
